title: SmartHire CV Analyzer
description: AI-powered resume analysis using RAG, AWS Bedrock, MongoDB, and GPT — with a Streamlit web app and recruiter-friendly features.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
markdown: kramdown
show_downloads: true
